FROM tiangolo/meinheld-gunicorn-flask:python3.8-alpine3.11

WORKDIR /app

RUN python -m pip install --upgrade pip

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY app/ .
